#!/bin/bash

set -ex

TOP_SRCDIR="$(dirname "$0")/.."
TOP_SRCDIR="$(cd "$TOP_SRCDIR" && pwd)"

LIBDIR="$TOP_SRCDIR/libchimp/.libs"

cmd='exec gdb "$TOP_SRCDIR/.libs/chimp"'

if [ "$(uname -r)" = "Darwin" ]; then
    cmd="DYLD_LIBRARY_PATH='$LIBDIR' $cmd"
else
    cmd="LD_LIBRARY_PATH='$LIBDIR' $cmd"
fi

eval "$cmd"

